build:
  environment:
    php: '8.3'
  image: default-bionic
  nodes:
    tests: true
    analysis:
      tests:
        override:
          - php-scrutinizer-run

filter:
  excluded_paths: ['tests/*']

tools:
  external_code_coverage: true
  php: 
    config:
      php_version: '8.3'
    remove_phpunit_assertions: true
    fix_php_opening_tag: true
    remove_php_closing_tag: true
    fix_line_ending: true
    fix_encoding: true
    enable_php_tidy: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: false
      order_alphabetically: true
    php_analyzer: true
    exception_name: "^[A-Z][a-zA-Z0-9]*Exception$"
    isser_method_name: "^(?:is|has|should|may|supports)"
    more_specific_types_in_doc_comments: true
    check_method_contracts:
      verify_interface_like_constraints: true
      verify_documented_constraints: true
      verify_parent_constraints: true
